
/**
	* Translation strings for UI
	* @type {Object}
	* @version v0.2
*/
const translatableStrings = {
    "text_editor.title": "Wesnoth File Editor",
    "text_editor.subtitle": "Create and manage Wesnoth scenario files with ease",
    "text_editor.how_to_use": "How to Use",
    "text_editor.step1": "Define your tags in the Teacher tab with keys and types",
    "text_editor.step2": "Save tags to dictionary using the Save button",
    "text_editor.step3": "Switch to Student tab to create content using defined tags",
    "text_editor.step4": "Click on tags in sidebar to insert templates",
    "text_editor.step5": "Validate files in Tester tab before use",
    "text_editor.teacher_tab": "Teacher",
    "text_editor.student_tab": "Student",
    "text_editor.tester_tab": "Tester",
    "text_editor.teacher_title": "Tag & Macros",
    "text_editor.tag_definition_title": "Tag Definition",
    "text_editor.dictionary": "Dictionary",
    "text_editor.dictionary_content": "Define your tags and their structure here. Each tag should have keys with specified types.",
    "text_editor.option_color": "Color",
    "text_editor.option_indentation": "Indentation",
    "text_editor.option_export": "Export",
    "text_editor.option_import": "Import",
    "text_editor.option_settings": "Settings",
    "text_editor.undo": "Undo",
    "text_editor.redo": "Redo",
    "text_editor.verify": "Verify",
    "text_editor.cancel": "Cancel",
    "text_editor.save": "Save",
    "text_editor.student_title": "Content Creation",
    "text_editor.student_dictionary_content": "Use the defined tags to create your scenario content. Click on a tag in the sidebar to insert it.",
    "text_editor.option_preview": "Preview",
    "text_editor.option_guides": "Guides",
    "text_editor.option_templates": "Templates",
    "text_editor.available_tags": "Available Tags",
    "text_editor.tester_title": "File Validation",
    "text_editor.tester_dictionary_content": "Validate your scenario files and check for errors or inconsistencies.",
    "text_editor.option_lint": "Lint",
    "text_editor.option_simulate": "Simulate",
    "text_editor.option_debug": "Debug",
    "text_editor.export_cfg": ".cfg",
    "text_editor.export_json": ".json",
    "text_editor.export_txt": ".txt",
    "text_editor.import_cfg": ".cfg",
    "text_editor.import_json": ".json",
    "text_editor.import_txt": ".txt",
    "text_editor.tooltip_color": "Change editor color scheme",
    "text_editor.tooltip_indentation": "Adjust indentation settings",
    "text_editor.tooltip_export": "Export your tag definitions",
    "text_editor.tooltip_import": "Import tag definitions",
    "text_editor.tooltip_settings": "Editor preferences",
    "text_editor.modal_title": "Tag Already Exists",
    "text_editor.modal_message": "The tag {tag} already exists. How would you like to proceed?",
    "text_editor.modal_replace": "Replace Existing",
    "text_editor.modal_append": "Add New Version",
    "text_editor.modal_cancel": "Cancel",
    "text_editor.save_manual": "Save Manual Entry",
    "text_editor.color_modal_title": "Color Assignment",
    "text_editor.color_reset": "Reset to Default",
    "text_editor.color_save": "Save Colors",
    "text_editor.color_cancel": "Cancel",
    "text_editor.color_item_tag": "Tag",
    "text_editor.color_item_key": "Key",
    "text_editor.color_item_color": "Color",
    "text_editor.define_new_tag": "Define New Tag",
    "text_editor.tag_keys": "Tag Keys",
    "text_editor.parse_form": "🔄 Parse & Update",
    "text_editor.clear_form": "🧹 Clear",
    "text_editor.save_entry": "💾 Save Entry",
    "text_editor.parse_success": "Form parsed successfully!",
	"text_editor.indentation_modal_title": "Indentation Settings",
	"text_editor.indentation_reset": "Reset to Default",
	"text_editor.indentation_save": "Save Settings",
	"text_editor.indentation_cancel": "Cancel",
	"text_editor.tooltip_indentation": "Adjust indentation settings",
    "text_editor.verify": "Verify",
    "text_editor.clear_confirm": "Are you sure you want to clear the form?",
    "text_editor.form_validation_error": "Form validation error",
    "text_editor.save_success": "Save successful!",
	"text_editor.currently_defined": "Currently defined tags:",
	"text_editor.table_header_tag_name": "Tag Name",
	"text_editor.table_header_keys": "Keys",
	"text_editor.table_header_actions": "Actions",
	"text_editor.edit": "Edit",
	"text_editor.delete": "Delete",
	"text_editor.manual_entry_title": "Manual Tag Entry",
	"text_editor.manual_syntax_title": "Tag Definition Syntax",
	"text_editor.manual_instruction": "Enter your tags using the following format:",
	"text_editor.tag_syntax_example": "[tag_name]\n\tkey1 = \"default_value\" (type, mandatory, scope)\n\tkey2 = \"default_value\" (type, mandatory, scope)\n\tnested_tags=\"Comma  separated list\"\n[/tag_name]",
	"text_editor.example_with_comments": "Example with comments:",
	"text_editor.tag_example": "[foreach] # This is a tag comment\n\tarray=\"\" (string, mandatory, official) # This is a key comment\n\tnested_tags=\"do\"\n[/foreach] # End of foreach",
	"text_editor.supported_types": "Supported types:",
	"text_editor.mandatory_label": "Mandatory:",
	"text_editor.scope_label": "Scope:",
	"text_editor.manual_textarea_placeholder": "Paste your tag definitions here...",
	"text_editor.tag_name_label": "Tag Name",
	"text_editor.tag_description_label": "Description",
	"text_editor.nested_tags_label": "Nested Tags",
	"text_editor.key_name_label": "Key Name",
	"text_editor.key_default_label": "Default Value",
	"text_editor.key_type_label": "Type",
	"text_editor.key_mandatory_label": "Mandatory",
	"text_editor.key_scope_label": "Scope",
	"text_editor.key_comment_label": "Comment",
	"text_editor.add_key_button": "Add Key",
	"text_editor.preview_title": "Preview",
	"text_editor.type_string": "String",
	"text_editor.type_translatable": "Translatable String",
	"text_editor.type_integer": "Integer",
	"text_editor.type_numeric": "Numeric",
	"text_editor.type_boolean": "Boolean",
	"text_editor.type_path": "Path",
	"text_editor.mandatory": "Mandatory",
	"text_editor.optional": "Optional",
	"text_editor.official": "Official",
	"text_editor.umc": "UMC",
	"text_editor.remove_key": "Remove",
	"text_editor.clear_button": "Clear",
	"text_editor.color_by_type": "Color by Type",
	"text_editor.bold_by_mandatory": "Bold by Mandatory",
	"text_editor.italic_by_scope": "Italic by Scope",
	"text_editor.mandatory_keys": "Mandatory Keys",
	"text_editor.optional_keys": "Optional Keys",
	"text_editor.official_scope": "Official Scope",
	"text_editor.umc_scope": "UMC Scope",
	"text_editor.indent_method_label": "Method",
	"text_editor.indent_tabs_label": "Tabs",
	"text_editor.indent_spaces_label": "Spaces",
	"text_editor.indent_size_label": "Size",
	"text_editor.spaces_per_indent_label": "Spaces per indent level:",
	"text_editor.tabs_per_indent_label": "Tabs per indent level:",
	"text_editor.tab_count_label": "Tab count:",
	"text_editor.tags_available": "Tags available:",
	"text_editor.last_validation": "Last validation:",
	"text_editor.no_validation": "No validation performed yet",
	"text_editor.option_stats": "Stats",
	"text_editor.footer": "Wesnoth File Editor v1.0 • Battle For Wesnoth • All tags and properties are preserved",
	"text_editor.tag_name_placeholder": "Enter tag name (e.g., part)",
	"text_editor.description_placeholder": "Tag description (optional)",
	"text_editor.nested_tags_placeholder": "Comma separated (e.g., do, then)",
	"text_editor.key_name_placeholder": "Key name",
	"text_editor.default_value_placeholder": "Default value",
	"text_editor.comment_placeholder": "Comment (optional)",
	"text_editor.tester_placeholder": "Enter scenario content here",
	"text_editor.or": "or",
    "text_editor.line_number_error": "Error updating line numbers",
    "text_editor.save_tag_error": "Error saving tag definition",
    "text_editor.get_tag_error": "Error getting tag definitions",
    "text_editor.insert_tag_error": "Error inserting tag",
    "text_editor.student_tag_error": "Error updating student tag list",
    "text_editor.insert_template_error": "Error inserting tag template",
    "text_editor.none": "None",
    "text_editor.dictionary_update_error": "Error updating dictionary table",
    "text_editor.color_highlight_error": "Error applying color highlighting",
    "text_editor.save_style_error": "Error saving style settings",
    "text_editor.load_definition_error": "Error loading tag definition",
    "text_editor.delete_definition_error": "Error deleting tag definition",
    "text_editor.parse_error": "Error parsing content",
    "text_editor.update_line_numbers_error": "Error updating line numbers",
    "text_editor.tab_switch_error": "Error switching tabs",
    "text_editor.save_tag_error": "Error saving tag definition",
    "text_editor.update_tag_list_error": "Error updating tag list",
    "text_editor.update_student_tag_error": "Error updating student tag list",
    "text_editor.tag_insert_error": "Error inserting tag",
    "text_editor.tag_template_error": "Error creating tag template",
    "text_editor.color_highlight_error": "Error applying color highlighting",
    "text_editor.add_key_error": "Error adding key",
    "text_editor.key_remove_error": "Error removing key",
    "text_editor.form_validation_error": "Form validation error",
    "text_editor.tag_name_empty": "Tag name cannot be empty",
    "text_editor.update_dictionary_error": "Error updating dictionary",
    "text_editor.parse_manual_error": "Error parsing manual input",
    "text_editor.feedback_error": "Error showing feedback",
    "text_editor.none": "None",
    "text_editor.key_name_label": "Key Name",
    "text_editor.key_default_label": "Default Value",
    "text_editor.key_type_label": "Type",
    "text_editor.key_mandatory_label": "Mandatory",
    "text_editor.key_scope_label": "Scope",
    "text_editor.key_name_placeholder": "key_name",
    "text_editor.default_value_placeholder": '""',
    "text_editor.type_string": "String",
    "text_editor.type_translatable": "Translatable String",
    "text_editor.type_integer": "Integer",
    "text_editor.type_numeric": "Numeric",
    "text_editor.type_boolean": "Boolean",
    "text_editor.type_path": "Path",
    "text_editor.mandatory": "Mandatory",
    "text_editor.optional": "Optional",
    "text_editor.official": "Official",
    "text_editor.umc": "UMC",
    "text_editor.edit": "Edit",
    "text_editor.delete": "Delete",
    "text_editor.mandatory_short": "M",
    "text_editor.optional_short": "O",
    "text_editor.official_short": "O",
    "text_editor.umc_short": "U",
    "text_editor.error_tag_name_empty": "Tag name cannot be empty",
    "text_editor.cursor_restore_error": "Error restoring cursor position",
    "text_editor.preview_error": "Error updating tag preview",
    "text_editor.form_validation_error": "Form validation error",
    "text_editor.key_name_label": "Key Name",
    "text_editor.key_default_label": "Default Value",
    "text_editor.key_type_label": "Type",
    "text_editor.key_mandatory_label": "Mandatory",
    "text_editor.key_scope_label": "Scope",
    "text_editor.key_comment_label": "Comment",
    "text_editor.type_string": "String",
    "text_editor.type_translatable": "Translatable String",
    "text_editor.type_integer": "Integer",
    "text_editor.type_numeric": "Numeric",
    "text_editor.type_boolean": "Boolean",
    "text_editor.type_path": "Path",
    "text_editor.mandatory": "Mandatory",
    "text_editor.optional": "Optional",
    "text_editor.official": "Official",
    "text_editor.umc": "UMC",
    "text_editor.remove_key": "Remove",
    "text_editor.key_name_placeholder": "Key name",
    "text_editor.default_value_placeholder": "Default value",
    "text_editor.comment_placeholder": "Comment (optional)",
    "text_editor.error_adding_key": "Error adding key",
    "text_editor.error_removing_key": "Error removing key",
    "text_editor.error_updating_preview": "Error updating preview",
    "text_editor.error_saving_tag": "Error saving tag",
    "text_editor.error_parsing_manual": "Error parsing manual input",
    "text_editor.error_saving_manual": "Error saving manual entry",
    "text_editor.error_clearing_form": "Error clearing form",
    "text_editor.error_saving_entry": "Error saving entry",
    "text_editor.error_opening_styles": "Error opening style settings",
    "text_editor.error_saving_styles": "Error saving styles",
    "text_editor.general_error": "An error occurred: ",
    "text_editor.confirm_delete_tag": "Are you sure you want to delete this tag definition?",
    "text_editor.saved_feedback": "✓ Saved!",
    "text_editor.save": "Save"
};